config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
  	resource :post_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :update] do
  	resource :follows, only: [:index, :show]
  	resource :followers, only: [:index, :show]
  end
  resources :relationships, only: [:create, :destroy]
  get '/home/about' , to: 'top#about'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  attachment :profile_image
  validates :name, presence: true
  validates :name,    length: { minimum: 2 }
  validates :name,    length: { maximum: 20 }
  validates :introduction,    length: { maximum: 50 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  def self.search(method,search)
          if method == "forward_match"
                        @users = User.where("name LIKE?","#{search}%")
                elsif method == "backward_match"
                        @users = User.where("name LIKE?","%#{search}")
                elsif method == "perfect_match"
                        @users = User.where("name LIKE?","#{search}")
                elsif method == "partial_match"
                        @users = User.where("name LIKE?","%#{search}%")
                else
                        @users = User.all
                end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
		@books = @user.books.page(params[:page]).reverse_order
		@book = Book.new
		if @user == current_user
			gon.address = @user.address_city + @user.address_street + @user.address_building
		end
	end
	def index
		@user = User.new
		method = flash[:f_users]
		search = flash[:w_users]
		@users = User.search(method,search)
		@book = Book.new
		@books = Book.all
	end
	def update
		@user = User.find(params[:id])
    	if @user.update(user_params)
    		flash[:notice]="You have updated user successfully."
    		redirect_to user_path(@user)
    	else
    		flash[:notice]="error"
    		render :edit
    	end
	end
	def edit
		@user = User.find(params[:id])
		if @user==current_user
		else
			redirect_to user_path(current_user)
		end
	end
	private
	def user_params
    	params.require(:user).permit(:name, :profile_image, :introduction, :postcode, :prefecture_code, :address_city, :address_street, :address_building)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb


<div class="container">
    <div class="row">
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
        <div class="col-xs-3">
<%= form_for(@user) do |f| %>
    <h2>User info</h2>
    <Label>Name</Label>
        <%= f.text_field :name, autofocus: true, class:"form-control", id:"inputEmail", placeholder:"名前"%>
    <label>Image</label>
    <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
    <label>Introduction</label>
        <%= f.text_area :introduction, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
        <label>zip code</label>
        <%= f.text_field :postcode, class:"form-control postal-code" %>
        <label>prefecture</label>
        <%= f.collection_select :prefecture_code, JpPrefecture::Prefecture.all, :name, :name, include_blank: true %><br>
        <label>city</label>
        <%= f.text_field :address_city, class:"form-control p-locality" %>
        <label>street</label>
        <%= f.text_field :address_street, class:"form-control p-street-address" %>
        <label>builbding name</label>
        <%= f.text_field :address_building, class:"form-control p-extended-address" %>
    <%= f.submit "Update User", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>
</div>
</div>
</div>

app/views/users/index.html.erb

<div class="container">
	<div class="row">
		<% if flash[:notice] %>
	<p id=notice><%= flash[:notice] %></p>
<% end %>
<%= render 'layouts/mypageuser', user: @user, book: @book %>
<div class="col-xs-9">
	<h2>Users</h2>
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th>フォロー</th>
			<th>フォロワー</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<% @users.each do |user| %>
		<tr>
			<td><%= link_to attachment_image_tag(user, :profile_image,  format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: '40x40'), user_path(user) %></td>
			<td><%= user.name %></td>
			<td><%= user.followings.count %></td>
			<td><%= user.followers.count %></td>
			<td><%= link_to "Show", user_path(user) %></td>
		</tr>
	<% end %>
	</tbody>
</table>
</div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
<div class="row">
	<% if flash[:notice] %>
	<p id=notice><%= flash[:notice] %></p>
<% end %>
<%= render 'layouts/userpage', {user: @user, book: @book} %>
<div class="col-xs-9">
	<h2>Books</h2>
<table class="table">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th>Favorite</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
	<% @books.each do |book| %>
		<tr>
			<td><%= attachment_image_tag @user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img tableimage", fallback: "no_image.jpg", size:'40x40' %></td>
			<td><%= link_to book.title, book_path(book) %></td>
			<td><%= book.body %></td>
			<td><i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
      		<%= book.favorites.count %> いいね</td>
      		<td>コメント数：<%= book.post_comments.count %></td>
		</tr>
	<% end %>
	</tbody>
</table>
</div>
</div>
<% if @user == current_user %>
<div class="row">
	<div class="col-xs-12">
<div id='map'></div>

<style>
#map{
  height: 400px;
}
</style>

<script>

let map
let geocode

function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
  center: {lat: -34.397, lng: 150.644},
  zoom: 8
  });

  let Address = gon.address;

  geocoder.geocode( { 'address': Address}, function(results, status) {
    if (status == 'OK') {
      map.setCenter(results[0].geometry.location);
      var marker = new google.maps.Marker({
          map: map,
          position: results[0].geometry.location
      });
    } else {
      alert('Geocode was not successful for the following reason: ' + status);
    }
  });
}
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&callback=initMap" async defer></script>
	</div>
</div>
<% end %>
</div>