config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
  	resource :post_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :update] do
  	resource :follows, only: [:index, :show]
  	resource :followers, only: [:index, :show]
  end
  resources :relationships, only: [:create, :destroy]
  get '/home/about' , to: 'top#about'
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
	validates :body,    length: { maximum: 200 }
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
    def self.search(method,search)
    			if method == "forward_match"
                        @books = Book.where("title LIKE?","#{search}%")
                elsif method == "backward_match"
                        @books = Book.where("title LIKE?","%#{search}")
                elsif method == "perfect_match"
                        @books = Book.where("title LIKE?","#{search}")
                elsif method == "partial_match"
                        @books = Book.where("title LIKE?","%#{search}%")
                else
                        @books = Book.all
                end
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    def edit
        @book = Book.find(params[:id])
        if @book.user==current_user
        else
            redirect_to books_path
        end
    end
    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice]="You have updated book successfully."
            redirect_to book_path(@book)
        else
            flash[:notice]="error"
            render :edit
        end
    end
    def create
    	@book = Book.new(book_params)
        @books = Book.all
        @book.user_id = current_user.id
        @user = User.new
        if @book.save
            flash[:notice] ="You have creatad book successfully."
            redirect_to book_path(@book)
        else
            render 'index'
        end
    end
    def index
    	@book = Book.new
        @user = User.new
        method = params[:search_method]
        search = params[:search_word]
        target = params[:search_target]
        if target == "book"
            @books = Book.search(method,search)
        elsif target == "user"
            flash[:f_users] = method
            flash[:w_users] = search
            redirect_to users_path
        else
            @books = Book.all
            @users = User.all
        end
    end
    def show
        @book = Book.find(params[:id])
        @name = @book.user.name
        @user = @book.user
        @book_1 = Book.new
        @post_comment_new = PostComment.new

    end
    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path

    end
    private
    def book_params
  		params.require(:book).permit(:title, :body, :user_id)
    end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb

<div class="container">
    <div class="row">
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
        <div class="col-xs-3">
<%= form_for(@book) do |f| %>
    <h2>Editing Book</h2>
    <Label>Title</Label>
        <%= f.text_field :title, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
    <label>Body</label>
        <%= f.text_area :body, autofocus: true, class:"form-control", id:"inputEmail", placeholder:""%>
    <%= f.submit "Update Book", class:"btn btn-lg btn-block btn-base-1 mt-20" %>
<% end %>
<%= link_to "Show", book_path(@book) %>
<%= link_to "Back", books_path %>
</div>
</div>
</div>

app/views/books/index.html.erb

<div class="container">
  <div class="row">
<% if flash[:notice] %>
  <p id=notice><%= flash[:notice] %></p>
<% end %>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="col-xs-3">
  <h2>User info</h2>
  <%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg"%>
  <table class="table">
    <tbody>
      <tr>
          <th>name</th>
          <th><%= current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%= current_user.introduction %></th>
        </tr>
        <tr>
          <th><%= link_to "フォロー", user_follows_path(current_user) %></th>
          <th><%= current_user.followings.count %></th>
        </tr>
        <tr>
          <th><%= link_to "フォロワー", user_followers_path(current_user) %></th>
          <th><%= current_user.followers.count %></th>
        </tr>
      </tbody>
    </table>
        <div class="row">
      <div class="col-xs-12">
        <%= link_to "", edit_user_path(current_user), class: "btn btn-default glyphicon glyphicon-wrench btn-block" %>
      </div>
  </div>
<h2>New book</h2>
<%= form_for(@book) do |f| %>
  <div class="form-group row">
    <label for="book_title">Title</label><br>
    <%= f.text_field :title, class:'col-xs-12' %>
  </div>
  <div class="form-group row">
    <label for="book_body">Body</label><br>
    <%= f.text_area :body, class:'col-xs-12' %>
  </div>
  <div class="actions row">
    <%= f.submit 'Create Book', class:'btn btn-primary col-xs-12' %>
  </div>
<% end %>
<br>
<h2>Search</h2>
</div>
<div class="col-xs-9">
  <h2>Books</h2>
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>title</th>
      <th>opinion</th>
      <th>Favorite</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr>
      <td><%= link_to attachment_image_tag(book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size:'40x40'), user_path(book.user) %></td>
      <td><%= link_to book.title, book_path(book) %></td>
      <td><%= book.body %></td>
      <td><div id="likes_buttons_<%= book.id %>"><%= render partial: 'layouts/like', locals: { book: book} %></div></td>
      <td>コメント数：<%= book.post_comments.count %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>
<% if flash[:notice] %>
  <p id=notice><%= flash[:notice] %></p>
<% end %>

</div>
</div>

app/views/books/show.html.erb

<div class="container">
	<div class="row">
		<% if flash[:notice] %>
	<p id=notice><%= flash[:notice] %></p>
<% end %>
<%= render 'layouts/mypagebook', {user: @user, book: @book_1} %>
<div class="col-xs-9">
	<h2>Book detail</h2>
	<table class="table">
		<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<% if @book.user == current_user %>
  			<th></th>
  			<th></th>
			<% end %>
		</tr>
		</thead>
		<tbody>
			<tr>
			<td><%= link_to attachment_image_tag(@book.user, :profile_image,  format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: '40x40'), user_path(@book.user) %><%= link_to @name , user_path(@book.user) %></td>
			<td><%= @book.title %></td>
			<td><%= @book.body %></td>
			<% if @book.user == current_user %>
  			<td><%= link_to "Edit", edit_book_path(@book), class: "btn btn-success" %></td>
  			<td><%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: '本当に削除しますか?' } , class: "btn btn-danger" %></td>
			<% end %>
		</tr>


		</tbody>
	</table>
  <div id="likes_buttons_<%= @book.id %>">
             <%= render partial: 'layouts/like', locals: { book: @book} %>
  </div>
<div id="comment_form_<%= @book.id %>">
             <%= render partial: 'layouts/comment', locals: { book: @book, post_comment: @post_comment_new} %>
  </div>
</div>
</div>
</div>