config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
  	resource :post_comments, only: [:create, :destroy]
  	resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :update] do
  	resource :follows, only: [:index, :show]
  	resource :followers, only: [:index, :show]
  end
  resources :relationships, only: [:create, :destroy]
  get '/home/about' , to: 'top#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true
	validates :body,    length: { maximum: 200 }
	has_many :post_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end
    def self.search(method,search)
    			if method == "forward_match"
                        @books = Book.where("title LIKE?","#{search}%")
                elsif method == "backward_match"
                        @books = Book.where("title LIKE?","%#{search}")
                elsif method == "perfect_match"
                        @books = Book.where("title LIKE?","#{search}")
                elsif method == "partial_match"
                        @books = Book.where("title LIKE?","%#{search}%")
                else
                        @books = Book.all
                end
	end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
  	belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user
    belongs_to :book

    validates :comment, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :user
  	belongs_to :follow, class_name: 'User'

  	validates :user_id, presence: true
  	validates :follow_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user
  attachment :profile_image
  validates :name, presence: true
  validates :name,    length: { minimum: 2 }
  validates :name,    length: { maximum: 20 }
  validates :introduction,    length: { maximum: 50 }

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  def self.search(method,search)
          if method == "forward_match"
                        @users = User.where("name LIKE?","#{search}%")
                elsif method == "backward_match"
                        @users = User.where("name LIKE?","%#{search}")
                elsif method == "perfect_match"
                        @users = User.where("name LIKE?","#{search}")
                elsif method == "partial_match"
                        @users = User.where("name LIKE?","%#{search}%")
                else
                        @users = User.all
                end
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    def edit
        @book = Book.find(params[:id])
        if @book.user==current_user
        else
            redirect_to books_path
        end
    end
    def update
        @book = Book.find(params[:id])
        if @book.update(book_params)
            flash[:notice]="You have updated book successfully."
            redirect_to book_path(@book)
        else
            flash[:notice]="error"
            render :edit
        end
    end
    def create
    	@book = Book.new(book_params)
        @books = Book.all
        @book.user_id = current_user.id
        @user = User.new
        if @book.save
            flash[:notice] ="You have creatad book successfully."
            redirect_to book_path(@book)
        else
            render 'index'
        end
    end
    def index
    	@book = Book.new
        @user = User.new
        method = params[:search_method]
        search = params[:search_word]
        target = params[:search_target]
        if target == "book"
            @books = Book.search(method,search)
        elsif target == "user"
            flash[:f_users] = method
            flash[:w_users] = search
            redirect_to users_path
        else
            @books = Book.all
            @users = User.all
        end
    end
    def show
        @book = Book.find(params[:id])
        @name = @book.user.name
        @user = @book.user
        @book_1 = Book.new
        @post_comment_new = PostComment.new

    end
    def destroy
        @book = Book.find(params[:id])
        @book.destroy
        redirect_to books_path

    end
    private
    def book_params
  		params.require(:book).permit(:title, :body, :user_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@book = Book.find(params[:book_id])
    book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: @book.id)
        favorite.save
  	end
  	def destroy
  		@book = Book.find(params[:book_id])
      book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: @book.id)
        favorite.destroy
  	end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	def index
	end
	def show
		@user = User.find(params[:user_id])
		@follows = @user.followings
		@book = Book.new
	end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
		@user = User.find(params[:id])
		@books = @user.books.page(params[:page]).reverse_order
		@book = Book.new
		if @user == current_user
			gon.address = @user.address_city + @user.address_street + @user.address_building
		end
	end
	def index
		@user = User.new
		method = flash[:f_users]
		search = flash[:w_users]
		@users = User.search(method,search)
		@book = Book.new
		@books = Book.all
	end
	def update
		@user = User.find(params[:id])
    	if @user.update(user_params)
    		flash[:notice]="You have updated user successfully."
    		redirect_to user_path(@user)
    	else
    		flash[:notice]="error"
    		render :edit
    	end
	end
	def edit
		@user = User.find(params[:id])
		if @user==current_user
		else
			redirect_to user_path(current_user)
		end
	end
	private
	def user_params
    	params.require(:user).permit(:name, :profile_image, :introduction, :postcode, :prefecture_code, :address_city, :address_street, :address_building)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
	
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_comment.html.erb
<div class="comment-list bt style-2" id="comments">
            <div class="float-wrapper">
                <h2 class="comment-count"><%= book.post_comments.count %>件コメント</h2>
            </div>
        </div>
<ol>
    <% book.post_comments.each do |post_comment| %>
        <li class="comment">
            <div class="comment-body bb">
                <div class="comment-avatar">
                    <div class="avatar">
                        <%= link_to attachment_image_tag(post_comment.user, :profile_image,  format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size: '40x40'), user_path(post_comment.user) %>
                    </div>
                </div>
                <div class="comment-text">
                    <div class="comment-author clearfix">
                        <a href="#" class="link-author"><%= link_to post_comment.user.name , user_path(post_comment.user) %></a>
                        <span class="comment-meta">
                          <span class="comment-date"><%= post_comment.created_at.strftime('%Y/%m/%d') %></span>
                        </span>
                    </div>
                    <div class="comment-entry"><%= post_comment.comment %></div>
                </div>
                <% if post_comment.user == current_user %>
                <%= link_to "削除", book_post_comments_path(id: post_comment, book_id: book), method: :delete, remote: true, class:'btn btn-danger' %>
                <% end %>
            </div>
        </li>
    <% end %>

</ol>
<%= form_with model: [book, post_comment], data: { remote: true } do |f| %>
    <div class="row">
        <div class="col-sm-12">
            <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
        </div>
    </div>
    <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/layouts/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/layouts/_like.html.erb
<% if book.favorited_by?(current_user) %>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
      <%= book.favorites.count %> いいね
    <% end %>
<% else %>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      <i class="fa fa-heart-o" aria-hidden="true"></i>
      <%= book.favorites.count %> いいね
    <% end %>
<% end %>
<% book.favorites.each do |favorite| %>
<a href="#" class="link-author"><%= link_to favorite.user.name , user_path(favorite.user) %></a>
<% end %>

app/views/layouts/_mypagebook.html.erb

<div class="col-xs-3">
	<h2>User info</h2>
	<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
	<table class="table">
		<tbody>
			<tr>
    			<th>name</th>
    			<th><%= current_user.name %></th>
    		</tr>
    		<tr>
    			<th>introduction</th>
    			<th><%= current_user.introduction %></th>
    		</tr>
    		<tr>
    			<th><%= link_to "フォロー", user_follows_path(current_user) %></th>
    			<th><%= current_user.followings.count %></th>
    		</tr>
    		<tr>
    			<th><%= link_to "フォロワー", user_followers_path(current_user) %></th>
    			<th><%= current_user.followers.count %></th>
    		</tr>
    	</tbody>
    </table>
        <div class="row">
    	<div class="col-xs-12">
        <%= link_to "", edit_user_path(@user), class: "btn btn-default glyphicon glyphicon-wrench btn-block" %>
    	</div>
	</div>
          <h2>New book</h2>
<%= form_for(book) do |f| %>
	<div class="form-group row">
		<label for="book_title">Title</label><br>
		<%= f.text_field :title, class:'col-xs-12' %>
	</div>
	<div class="form-group row">
		<label for="book_body">Body</label><br>
		<%= f.text_area :body, class:'col-xs-12' %>
	</div>
	<div class="actions row">
		<%= f.submit 'Create Book', class:'btn btn-primary col-xs-12' %>
	</div>
<% end %>
<br>
</div>

app/views/layouts/_mypageuser.html.erb
<div class="col-xs-3">
	<h2>User info</h2>
	<%= attachment_image_tag current_user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
	<table class="table">
		<tbody>
			<tr>
    			<th>name</th>
    			<th><%= current_user.name %></th>
    		</tr>
    		<tr>
    			<th>introduction</th>
    			<th><%= current_user.introduction %></th>
    		</tr>
    		<tr>
    			<th><%= link_to "フォロー", user_follows_path(current_user) %></th>
    			<th><%= current_user.followings.count %></th>
    		</tr>
    		<tr>
    			<th><%= link_to "フォロワー", user_followers_path(current_user) %></th>
    			<th><%= current_user.followers.count %></th>
    		</tr>
    	</tbody>
    </table>
    <div class="row">
    	<div class="col-xs-12">
        <%= link_to "", edit_user_path(current_user), class: "btn btn-default glyphicon glyphicon-wrench btn-block" %>
    	</div>
	</div>
	<h2>New book</h2>
<%= form_for(book) do |f| %>
	<div class="form-group row">
		<label for="book_title">Title</label><br>
		<%= f.text_field :title, class:'col-xs-12' %>
	</div>
	<div class="form-group row">
		<label for="book_body">Body</label><br>
		<%= f.text_area :body, class:'col-xs-12' %>
	</div>
	<div class="actions row">
		<%= f.submit 'Create Book', class:'btn btn-primary col-xs-12' %>
	</div>
<% end %>
</div>

app/views/layouts/_notifications.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: #{key}) %>
<% end %>

app/views/layouts/_userpage.html.erb
<div class="col-xs-3">
	<h2>User info</h2>
	<%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
	<table class="table">
		<tbody>
			<tr>
    			<th>name</th>
    			<th><%= user.name %></th>
    			<th></th>
    		</tr>
    		<tr>
    			<th>introduction</th>
    			<th><%= user.introduction %></th>
    		</tr>
    		<tr>
    			<th><%= link_to "フォロー", user_follows_path(user) %></th>
    			<th><%= user.followings.count %></th>
    		</tr>
    		<tr>
    			<th><%= link_to "フォロワー", user_followers_path(user) %></th>
    			<th><%= user.followers.count %></th>
    		</tr>
    		<tr>
    			<th><%= render 'layouts/follow_button', user: @user %></th>
    		</tr>
    	</tbody>
    </table>
    <div class="row">
    	<div class="col-xs-12">
        <%= link_to "", edit_user_path(@user), class: "btn btn-default glyphicon glyphicon-wrench btn-block" %>
    	</div>
	</div>
	<h2>New book</h2>
<%= form_for(book) do |f| %>
	<div class="form-group row">
		<label for="book_title">Title</label><br>
		<%= f.text_field :title, class:'col-xs-12' %>
	</div>
	<div class="form-group row">
		<label for="book_body">Body</label><br>
		<%= f.text_area :body, class:'col-xs-12' %>
	</div>
	<div class="actions row">
		<%= f.submit 'Create Book', class:'btn btn-primary col-xs-12' %>
	</div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
    <title>Bookers2</title>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
  <div class="container-fluid">
    <div class="navbar-header">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      <a class="navbar-brand">Bookers</a>
    </div>
    <div class="collapse navbar-collapse" id="navbarEexample1">
      <div class="navbar-right">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li><span class="glyphicon glyphicon-home"><%= link_to " Home", user_path(current_user) %></span></li>
        <li><span class="glyphicon glyphicon-user"><%= link_to ' Users', users_path %></span></li>
        <li><span class="glyphicon glyphicon-book"><%= link_to ' Books', books_path %></span></li>
        <li><span class="glyphicon glyphicon-log-out"><%= link_to " logout", destroy_user_session_path, method: :delete %></span></li>
        <% else %>
        <li><span class="glyphicon glyphicon-home"><%= link_to " Home", root_path %></span></li>
        <li><span class="glyphicon glyphicon-link"><%= link_to " About", home_about_path %></span></li>
        <li><span class="glyphicon glyphicon-edit"><%= link_to " Sign up", new_user_registration_path %></span></li>
        <li><span class="glyphicon glyphicon-log-in"><%= link_to " login", new_user_session_path %></span></li>
        <% end %>
      </ul>
    </div>
    </div>
  </div>
</div>
  </header>
  <% if user_signed_in? %>
  <div class="container">
    <div class="row">
      <div class="col-xs-4 col-xs-offset-4">
  <%= form_tag books_path, class:'justify-content-center searchform', :method => 'get' do %>
            <%= select(@search_content, :search_target, [["本","book"], ["ユーザー","user"]])%>
            <%= select(@search_content, :search_method, [["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]])%>
            <%= text_field(@search_content, :search_word)%>
            <%= submit_tag "検索", :title => nil, class:'btn btn-default'%>
          <% end %>
          <% end %>
        </div>
        <div class="col-xs-4">
        </div>
      </div>
    </div>
    <%= yield %>
    <footer><div class="container">
      <div class="row">
        <div id="footer" class="col-xs-3">
      <p>CopyRight Infratop.inc</p>
    </div>
  </div>
</div>
    </footer>
  </body>

</html>